### ISSUE TITLE
change to postgres

### ISSUE THREAD

**Issue by elmcrest** [APSL/docker-puput#4]
why on earth with mysql?? :)

**Comment by eduherraiz** [comment]
Thank you for your contribution @elmcrest!
I'm really happy to know you have enough time to spend in review old repos and say how people have to do the job. 
Are you interested in fork the repo and do the work with your proposal? We will accept contributions! :-D

**Comment by elmcrest** [comment]
you're welcome @eduherraiz - I'm always happy to help ;)
